//  WebserviceConstant.swift
import Foundation
let objWebserviceManager :WebServiceManager = WebServiceManager.sharedObject()
//MARK : - Webservices
struct WebURL {
    //LocalbaseURl
    //static let BaseUrl ="http://www.webdesky.com/demowork/adimvi/api/"
    //LivebaseURL
    static let BaseUrl =  "https://www.adimvi.com/appAPI/index.php/api/"
    static let ImageUrl =  "https://adimvi.com/?qa=image&qa_blobid="
    static let userlogin = "userlogin"
    static let userRegister = "userRegister"
    static let commentDelete = "commentDelete"
    static let getsales = "getsales"
    static let getfavourite = "getfavourite"
    static let getCategories = "getCategories"
    
    static let getFollowing = "getFollowing"
    static let getAllmembers = "getallmember"
    static let getCategoryByPost = "getCategoryByPost"
    static let popularTagPostList = "popularTagPostList"
    static let popularTagPostFollow = "popularTagPostFollow"
    
    static let getRecentPost = "getRecentPost"
    static let getMostVotedPost = "getMostVotedPost"
    static let getMostViewsPost = "getMostViewsPost"
    static let setfavourite = "setfavourite"
    static let changePassword = "changePassword"
    static let getProfile = "getProfile"
    static let editProfile = "editProfile"
    static let getPostDetail = "getPostDetail"
    static let LikePost = "setVote"
    static let getUserFollowing = "getUserFollowing"
    static let getUserFollowingNew = "getUserFollowingNew"
    static let setUserFollowing = "setUserFollowing"
    static let getParticularUserPost = "getParticularUserPost"
    static let getPostFollowing = "getPostFollowing"
    static let getPostFollowingTest = "getPostFollowingTest"
    static let followTagPostList = "followTagPostList"
    static let getUserPublications = "getUserPublications"
    static let getUserPublicationsNew = "getUserPublicationsNew"
    static let draftPostList = "draftPostList"
    static let draftPostDetail = "draftPostDetail"
    static let updatePost = "updatePost"
    static let categoryList = "categoryList"
    static let postComment = "postComment"
    static let postCommentList = "postCommentList"
    static let setPostReport = "setPostReport"
    static let addNewWall = "addWall"
    static let wallPostList = "wallPostList"
    static let allPrivateMessagesList = "allPrivateMessagesList"
    static let deleteWall = "deleteWall"
    static let editWall = "editWall"
    static let getFollowers = "getFollowers"
    static let getFollowersNew = "getFollowersNew"
    static let addPrivateMessages = "addPrivateMessagesNew"
    static let privateMessagesList = "privateMessagesList"
    static let CommentCommentList = "CommentCommentList"
    static let editHideShowpostComment = "editHideShowpostComment"
    static let relatedPostByCategory = "relatedPostByCategory"
    static let replyWallComments = "replyWallComments"
    static let wallCommentList = "wallCommentList"
    static let setWallfavourite = "setWallfavourite"
    static let postByTagList = "postByTagList"
    static let getPostListByTags = "getPostListByTags"
    static let buyPostList = "buyPostList"
    static let popularTagList = "popularTagList"
    static let followTagList = "followTagList"
    
    static let addNotes = "addNotes"
    static let notesList = "notesList"
    static let notesDelete = "notesDelete"
    static let updateNotes = "updateNotes"
    
    static let getProfileRecentPost = "getProfileRecentPost"
    static let getMemberList = "getMemberList"
    static let homeSearchAshu = "homeSearchAshu"
    static let homeSearch = "homeSearch"
    static let homeSearchNew = "homeSearchNew"
    static let userBalance = "userBalance"
    static let savecredit = "saveCreditTransaction"
    static let paymentGateway = "paymentGateway"
    static let contact = "contact"
    static let buyPost = "buyPost"
    static let wallFollowList = "wallFollowList"
    static let readMorePost = "readMorePost"
    static let postViewed = "postViewed"
    static let addRating = "addRating"
    
    static let mainNotification = "mainNotification"
    static let userRecentActivity = "userRecentActivity"
    static let postDelete = "postDelete"
    static let salesNotify = "salesNotify"
    static let allseenNotification = "allSeenNotification"
    static let seenNotification = "seenNotification"
    static let updateFcmDevice = "updateFCMDevice"
    static let GET_MUROS_BY_TAG = "popularTagMuroList";
    static let Fetch_All_Members = "fetchAllUser"
    
    
    static let GET_RECENT_WALL_USER = "recentWallUser"
    static let UPDATE_USER_PROFILE_VISIT = "updateUserProfileVisited"
    static let UPDATE_USER_REWALL_COUNT = "updateUserRewallCount"
    static let UPDATE_WALL_COUNT = "updateWallCount"
    
    static let ADD_ROOM: String = "addRoom"
    static let GET_ROOM_LIST: String = "getRoomList"
    static let JOIN_ROOM: String = "joinRoom"
    static let LEAVE_ROOM: String = "leaveRoom"
    static let CLOSE_ROOM: String = "closeRoom"
    static let ADD_ROOM_MESSAGE: String = "addRoomMessage"
    static let GET_ROOM_MESSAGE: String = "fetchRoomMessage"
    static let ADD_VOICE_ROOM_MESSAGE: String = "addVoiceRoomMessage"
    static let SET_FEATURE_POST: String = "setFeaturePost"
    static let SET_FEATURE_WALL: String = "setFavoriteWall"
}

let k_success = "success"

